version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./metrics:/app/metrics
    environment:
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
      - MAX_FILE_BYTES=524288000  # 500 MB
      - CORS_ORIGINS_JSON=["http://frontend:3000","http://localhost:3000","http://127.0.0.1:3000"]
    networks:
      - podpromo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000
      - BACKEND_ORIGIN=http://backend:8000
    depends_on:
      - backend
    networks:
      - podpromo

networks:
  podpromo:
    driver: bridge

volumes:
  uploads:
  outputs:
  metrics:
